project:
  type: website

execute:
  freeze: true

website:
  title: "extendr"
  site-url: https://extendr.github.io
  repo-url: https://github.com/extendr/extendr.github.io
  repo-branch: main
  repo-actions: [edit, issue]

  navbar:
    logo: /images/ferRis.png
    left:
      - text: "Get Started"
        href: get-started.qmd
      - text: "User Guide"
        href: user-guide/index.qmd
      - text: "API"
        href: https://extendr.github.io/extendr/extendr_api/
      - text: "Blog"
        href: blog/index.qmd
    right:
      - icon: github
        href: https://github.com/extendr/extendr
      - icon: discord
        href: https://discord.gg/7hmApuc

  sidebar:
    - title: "User Guide"
      collapse-level: 1
      style: "floating"
      contents:
        - user-guide/index.qmd
        - user-guide/complete-example.qmd
        - section: "R Packages"
          contents:
            - user-guide/r-pkgs/package-setup.qmd
            - user-guide/r-pkgs/package-structure.qmd
        - section: "Type Mapping"
          contents:
            - user-guide/type-mapping/extendr-macro.qmd
            - user-guide/type-mapping/scalars.qmd
            - user-guide/type-mapping/vectors.qmd
            - user-guide/type-mapping/missing-values.qmd
            - user-guide/type-mapping/characters.qmd
        - section: "Error Handling"
          contents:
            - user-guide/error-handling/basic-error-handling.qmd
        - user-guide/serde-integration.qmd
        - user-guide/cran-publishing.qmd
        - text: CRAN's MSRV
          href: user-guide/cran-msrv.qmd
        - text: WebR
          href: user-guide/webr.qmd
        - text: FAQ
          href: user-guide/faq.qmd

format:
  html:
    html-table-processing: none
    theme: css/_bootswatch.scss
    toc: false
    include-in-header:
      - text: |
          <script type="text/javascript" src="/js/breadcrumb-fix.js"></script>
